// <auto-generated />
using System;
using CounselFlow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CounselFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CounselFlow.Domain.Entities.Agent", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("text")
                        .HasColumnName("agentId");

                    b.Property<string>("ActiveYn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CrdDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AgentId");

                    b.ToTable("agent", (string)null);
                });

            modelBuilder.Entity("CounselFlow.Domain.Entities.Consult", b =>
                {
                    b.Property<string>("ConsultId")
                        .HasColumnType("text")
                        .HasColumnName("consultId");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .HasColumnType("text");

                    b.Property<DateTime>("CrdDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StdDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConsultId");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustomerId");

                    b.ToTable("consult", (string)null);
                });

            modelBuilder.Entity("CounselFlow.Domain.Entities.ConsultTag", b =>
                {
                    b.Property<string>("ConsultId")
                        .HasColumnType("text")
                        .HasColumnName("consultId");

                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tagId");

                    b.HasKey("ConsultId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("consultTag", (string)null);
                });

            modelBuilder.Entity("CounselFlow.Domain.Entities.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("text")
                        .HasColumnName("customerId");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CrdDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("CounselFlow.Domain.Entities.Tag", b =>
                {
                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tagId");

                    b.Property<DateTime>("CrdDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("CounselFlow.Domain.Entities.Consult", b =>
                {
                    b.HasOne("CounselFlow.Domain.Entities.Agent", "Agent")
                        .WithMany("Consults")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CounselFlow.Domain.Entities.Customer", "Customer")
                        .WithMany("Consults")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CounselFlow.Domain.Entities.ConsultTag", b =>
                {
                    b.HasOne("CounselFlow.Domain.Entities.Consult", "Consult")
                        .WithMany("ConsultTags")
                        .HasForeignKey("ConsultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CounselFlow.Domain.Entities.Tag", "Tag")
                        .WithMany("ConsultTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consult");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CounselFlow.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Consults");
                });

            modelBuilder.Entity("CounselFlow.Domain.Entities.Consult", b =>
                {
                    b.Navigation("ConsultTags");
                });

            modelBuilder.Entity("CounselFlow.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Consults");
                });

            modelBuilder.Entity("CounselFlow.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ConsultTags");
                });
#pragma warning restore 612, 618
        }
    }
}
